# Generated by Django 3.2.25 on 2024-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0017_auto_20200701_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logo/site')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site info',
                'verbose_name_plural': 'Sites infos',
            },
        ),
    ]
