# Generated by Django 3.2.25 on 2024-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elenizado', '0019_auto_20241126_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
